//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class config_rule
    {
        public int id { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public int state { get; set; }
        public System.DateTime add_time { get; set; }
        public string add_admin { get; set; }
        public string remark { get; set; }
    }
}
