//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.order = new HashSet<order>();
            this.user_product = new HashSet<user_product>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int period_time { get; set; }
        public decimal Calculate_the_force { get; set; }
        public decimal total_score { get; set; }
        public System.DateTime add_time { get; set; }
        public System.DateTime mod_time { get; set; }
        public decimal price { get; set; }
        public string unit { get; set; }
        public decimal first_level_referral_bonuses { get; set; }
        public decimal second_level_referral_bonuses { get; set; }
        public decimal first_level_earnings_bonuses { get; set; }
        public decimal second_level_earnings_bonuses { get; set; }
        public string product_img { get; set; }
        public string product_introduct { get; set; }
        public string remark { get; set; }
        public int sort { get; set; }
        public int del_flag { get; set; }
        public int product_count { get; set; }
        public int product_sold_count { get; set; }
        public int product_inventory_count { get; set; }
        public string add_admin { get; set; }
    
        public virtual ICollection<order> order { get; set; }
        public virtual ICollection<user_product> user_product { get; set; }
    }
}
