//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_msg_record
    {
        public int id { get; set; }
        public int type { get; set; }
        public Nullable<int> admin_id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public System.DateTime add_time { get; set; }
        public int sort { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> mod_time { get; set; }
        public int del_flag { get; set; }
        public Nullable<int> read_count { get; set; }
    
        public virtual administrator administrator { get; set; }
    }
}
