//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_log
    {
        public System.Guid id { get; set; }
        public System.DateTime add_time { get; set; }
        public int type { get; set; }
        public string content { get; set; }
        public string page_url { get; set; }
        public string add_name { get; set; }
        public string ip_address { get; set; }
    }
}
