//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.order = new HashSet<order>();
            this.user_address = new HashSet<user_address>();
            this.user_msg_record = new HashSet<user_msg_record>();
            this.user_product = new HashSet<user_product>();
            this.user_score_record = new HashSet<user_score_record>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string tel { get; set; }
        public int sex { get; set; }
        public int pid { get; set; }
        public decimal total_score { get; set; }
        public decimal usable_score { get; set; }
        public decimal yet_use_score { get; set; }
        public decimal total_pay { get; set; }
        public int total_product_count { get; set; }
        public int state { get; set; }
        public int isbuy { get; set; }
        public string qr_code { get; set; }
    
        public virtual ICollection<order> order { get; set; }
        public virtual ICollection<user_address> user_address { get; set; }
        public virtual ICollection<user_msg_record> user_msg_record { get; set; }
        public virtual ICollection<user_product> user_product { get; set; }
        public virtual ICollection<user_score_record> user_score_record { get; set; }
        public virtual wx_user wx_user { get; set; }
    }
}
