//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_msg_record
    {
        public int id { get; set; }
        public int msg_type { get; set; }
        public string title { get; set; }
        public string msg_content { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> admin_id { get; set; }
        public Nullable<int> msg_pid { get; set; }
        public System.DateTime add_time { get; set; }
        public int sort { get; set; }
        public int isread { get; set; }
        public int read_count { get; set; }
        public string remark { get; set; }
    
        public virtual administrator administrator { get; set; }
        public virtual user user { get; set; }
    }
}
