//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_score_record
    {
        public System.Guid id { get; set; }
        public int user_id { get; set; }
        public decimal score { get; set; }
        public int type { get; set; }
        public int state { get; set; }
        public string source_name { get; set; }
        public Nullable<int> source_id { get; set; }
        public string remark { get; set; }
        public System.DateTime add_time { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> rollout_address_id { get; set; }
        public string admin_remark { get; set; }
    
        public virtual order order { get; set; }
        public virtual user user { get; set; }
        public virtual user_address user_address { get; set; }
    }
}
