//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_request_rule
    {
        public wx_request_rule()
        {
            this.wx_request_content = new HashSet<wx_request_content>();
        }
    
        public int id { get; set; }
        public string rule_name { get; set; }
        public string req_keywords { get; set; }
        public int request_type { get; set; }
        public int response_type { get; set; }
        public int sort { get; set; }
        public System.DateTime add_time { get; set; }
    
        public virtual ICollection<wx_request_content> wx_request_content { get; set; }
    }
}
