//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_user
    {
        public int id { get; set; }
        public string gzh_openid { get; set; }
        public string unionid { get; set; }
        public string xcx_openid { get; set; }
        public string groupid { get; set; }
        public string nickname { get; set; }
        public string wx_head_protrait { get; set; }
        public int sex { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string language { get; set; }
        public System.DateTime add_time { get; set; }
        public string remark { get; set; }
        public int state { get; set; }
        public Nullable<System.DateTime> unsubscribe_time { get; set; }
        public string province { get; set; }
    
        public virtual user user { get; set; }
    }
}
